version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${HUB_USERNAME}/ui:${UI_VER}
    ports:
      - ${PUBLISHED_PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${HUB_USERNAME}/post:${POST_VER}
    networks:
      - back_net
      - front_net
  comment:
    image: ${HUB_USERNAME}/comment:${COMMENT_VER}
    networks:
      - back_net
      - front_net
  prometheus:
    image: ${HUB_USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
