version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      single_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${HUB_USERNAME}/ui:${UI_VER}
    ports:
      - ${PUBLISHED_PORT}:9292/tcp
    networks:
      - single_net
  post:
    image: ${HUB_USERNAME}/post:${POST_VER}
    networks:
      - single_net
  comment:
    image: ${HUB_USERNAME}/comment:${COMMENT_VER}
    networks:
      - single_net

volumes:
  post_db:

networks:
  single_net:
